// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJj2ztmYj3H8GbcWCvil5D4g7PGQ0g3tU',
    appId: '1:669297247888:web:0b16daf9209b6b493c7a15',
    messagingSenderId: '669297247888',
    projectId: 'instagram-dfcc3',
    authDomain: 'instagram-dfcc3.firebaseapp.com',
    storageBucket: 'instagram-dfcc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhxTcKOAqz0RND02OYymzuOCJQ0_H5wY',
    appId: '1:669297247888:android:0d1e3d9918e4f7753c7a15',
    messagingSenderId: '669297247888',
    projectId: 'instagram-dfcc3',
    storageBucket: 'instagram-dfcc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBXGMvrThG3V4H5jGiFGJu62E1Sw7omY',
    appId: '1:669297247888:ios:0602f4b1f2bd55c93c7a15',
    messagingSenderId: '669297247888',
    projectId: 'instagram-dfcc3',
    storageBucket: 'instagram-dfcc3.appspot.com',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBXGMvrThG3V4H5jGiFGJu62E1Sw7omY',
    appId: '1:669297247888:ios:7d7c4701ceda19913c7a15',
    messagingSenderId: '669297247888',
    projectId: 'instagram-dfcc3',
    storageBucket: 'instagram-dfcc3.appspot.com',
    iosBundleId: 'com.example.instaApp.RunnerTests',
  );
}
